GET http://localhost:3001/api/users/

###
post http://localhost:3001/api/notes
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJldmVuYW50IiwiaWQiOiI2MTgwNTY0MjFiYzcwZmIyOTcxZjU0YmIiLCJpYXQiOjE2MzU4MDA3NzV9.W4ZtarCmTIa8NEEt1xRpn9WWL0waw0l7_64ZzXITaBA

{
    "content": "sdfsdfsdfsddfiNDIA IS BEST ofsdfut there",
    "important":true
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
    "username":"mluukkai",
    "password":"salainen"
}

###
PUT http://localhost:3001/api/notes/617331fabe159e1e2e71aaf1
content-type: application/json

{
    "content": "sampfdsflgd;slfdfcdfsdadadfcasdfdfasasf",
    "important":false
}

###
DELETE http://localhost:3001/api/notes/617859ab280afcbb58258d9c

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "ram",
    "name": "toss",
    "password": "babu"
}

###
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "the world is straight",
    "important":true
}

###
POST http://localhost:3001/api/testing/reset HTTP/1.1
content-type: application/json


