GET http://localhost:3001/api/notes/
###
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "Aur batao sheela mausi jaun?",
    "important":true
}

###
PUT http://localhost:3001/api/notes/617331fabe159e1e2e71aaf1
content-type: application/json

{
    "content": "sampfdsflgd;slfdfcdfsdadadfcasdfdfasasf",
    "important":false
}

###
DELETE http://localhost:3001/api/notes/617859ab280afcbb58258d9c